# Generated by Django 5.2.10 on 2026-02-15 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_risky', models.BooleanField(default=False)),
                ('original_video', models.CharField(blank=True, max_length=200, null=True)),
                ('camera_type', models.CharField(choices=[('BODY', 'Body Cam'), ('FULL', 'Full Cam')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video',
                'ordering': ['-created_at'],
            },
        ),
    ]
