# Generated by Django 5.2.10 on 2026-02-19 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detect', '0001_initial'),
        ('worksession', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='worksession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_logs', to='worksession.worksession'),
        ),
        migrations.AddField(
            model_name='videologread',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videologread',
            name='videolog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='detect.videolog'),
        ),
        migrations.AlterUniqueTogether(
            name='videologread',
            unique_together={('videolog', 'manager')},
        ),
    ]
