# Generated by Django 5.2.10 on 2026-02-17 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
        ('worksession', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_type', models.CharField(choices=[('BODY', 'Body Cam'), ('FULL', 'Full Cam')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VideoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_logs', to='detect.risktype')),
                ('worksession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_logs', to='worksession.worksession')),
            ],
            options={
                'db_table': 'videolog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLogRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reads', to=settings.AUTH_USER_MODEL)),
                ('videolog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='detect.videolog')),
            ],
            options={
                'db_table': 'videolog_read',
                'unique_together': {('videolog', 'manager')},
            },
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
