# Generated by Django 5.2.10 on 2026-02-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_remove_compliance_is_updated_and_more'),
        ('detect', '0002_risktype_videolog_videologread_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='compliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='check.compliance'),
        ),
        migrations.AddField(
            model_name='videolog',
            name='source',
            field=models.CharField(choices=[('AUTO', 'Auto Detection'), ('MANUAL', 'Manual Report')], default='AUTO', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolog',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10, null=True),
        ),
    ]
