# Generated by Django 5.2.10 on 2026-02-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_videolog_compliance_videolog_source_videolog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolog',
            name='risk_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_logs', to='detect.risktype'),
        ),
    ]
