services:
  # 1. Database (Existing)
  db:
    image: mysql:8.0
    container_name: riskpulse_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:6
    container_name: riskpulse_redis
    ports:
      - "6379:6379"

  # 3. Backend (Django) - UPDATED
  backend:
    build: ./backend
    container_name: riskpulse_be

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306

      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    

    env_file:
      - ./backend/.env
  
    # Dev
    command: python manage.py runserver 0.0.0.0:8000

  # azurite:
  #   image: mcr.microsoft.com/azure-storage/azurite:3.29.0
  #   container_name: riskpulse_azurite
  #   command:
  #     - azurite-blob
  #     - --blobHost
  #     - 0.0.0.0
  #     - --blobPort
  #     - "10000"
  #     - --location
  #     - /data
  #     - --debug
  #     - /data/debug.log
  #   ports:
  #     - "10000:10000"
  #   volumes:
  #     - azurite_data:/data

    # For Deployment
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3

  # worker_risk:
  #   build: ./backend
  #   container_name: riskpulse_gpu_risk

  #   volumes:
  #     - ./backend:/app
  #     # If the worker needs to write to DB, share DB logic or use API
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started

  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  #   command: celery -A config worker -l info

  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_HOST=db
  #     - MYSQL_PORT=3306
  #     - DJANGO_SECRET_KEY=${SECRET_KEY}
  #     # Same Connection String as Backend

  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

volumes:
  db_data:
#   azurite_data:

