# Generated by Django 5.2.10 on 2026-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostWorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksession_id', models.IntegerField(db_index=True)),
                ('assessment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('report_version', models.PositiveIntegerField()),
                ('input_snapshot', models.JSONField()),
                ('report_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'postwork_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['worksession_id', '-report_version'], name='postwork_re_workses_41aa96_idx')],
                'unique_together': {('worksession_id', 'report_version')},
            },
        ),
    ]
