# Generated by Django 5.2.10 on 2026-02-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postworkreport',
            new_name='postwork_re_workses_2f2fe0_idx',
            old_name='postwork_re_workses_41aa96_idx',
        ),
        migrations.AlterModelTable(
            name='postworkreport',
            table='postwork_report',
        ),
    ]
