# Generated by Django 5.2.10 on 2026-02-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postworkreport',
            name='assessment_id',
        ),
    ]
