# Generated by Django 5.2.10 on 2026-02-12 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_path', models.CharField(db_index=True, max_length=255)),
                ('site_label', models.CharField(max_length=255)),
                ('work_type_fixed', models.CharField(max_length=255)),
                ('llm_result', models.JSONField()),
                ('overall_grade', models.CharField(db_index=True, max_length=16)),
                ('overall_max_R', models.IntegerField(db_index=True)),
                ('work_permission', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blob_path', 'created_at'], name='risk_assess_blob_pa_9f719e_idx'), models.Index(fields=['overall_grade', 'created_at'], name='risk_assess_overall_8d3fb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_version', models.CharField(default='v1', max_length=16)),
                ('scene_summary', models.JSONField()),
                ('hazards', models.JSONField()),
                ('overall', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report', to='risk.riskassessment')),
            ],
            options={
                'db_table': 'risk_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_risks', models.JSONField()),
                ('immediate_actions', models.JSONField()),
                ('short_message', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_recommendation', to='risk.riskassessment')),
            ],
            options={
                'db_table': 'worker_recommendations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
