# Generated by Django 5.2.10 on 2026-02-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('site_label', models.CharField(max_length=255)),
                ('llm_result', models.JSONField()),
                ('overall_grade', models.CharField(max_length=5)),
                ('overall_max_R', models.IntegerField()),
                ('work_permission', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'risk_assessment_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_version', models.CharField(default='v1', max_length=16)),
                ('scene_summary', models.JSONField()),
                ('hazards', models.JSONField()),
                ('overall', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'risk_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_risks', models.JSONField()),
                ('immediate_actions', models.JSONField()),
                ('short_message', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'worker_recommendations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
