# Generated by Django 5.2.10 on 2026-02-19 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0001_initial'),
        ('worksession', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='worksession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='worksession.worksession'),
        ),
        migrations.AddField(
            model_name='riskassessmentimage',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='risk.riskassessment'),
        ),
        migrations.AddField(
            model_name='riskreport',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report', to='risk.riskassessment'),
        ),
        migrations.AddField(
            model_name='workerrecommendation',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_recommendation', to='risk.riskassessment'),
        ),
        migrations.AddIndex(
            model_name='riskassessmentimage',
            index=models.Index(fields=['blob_name'], name='risk_assess_blob_na_f4062d_idx'),
        ),
    ]
