# Generated by Django 5.2.10 on 2026-02-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='blob_paths',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='RiskAssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_name', models.CharField(db_index=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='risk.riskassessment')),
            ],
            options={
                'db_table': 'risk_assessment_images',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['blob_name'], name='risk_assess_blob_na_f4062d_idx')],
            },
        ),
    ]
