# Generated by Django 5.2.10 on 2026-02-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_riskassessment_blob_paths_riskassessmentimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='riskreport',
            table='risk_report',
        ),
    ]
