# Generated by Django 5.2.10 on 2026-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_alter_riskassessment_llm_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='overall_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
