# Generated by Django 5.2.10 on 2026-02-15 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complied', models.BooleanField(default=False)),
                ('target', models.CharField(max_length=50)),
                ('original_image', models.CharField(blank=True, max_length=200, null=True)),
                ('detected_image', models.CharField(blank=True, max_length=200, null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance',
                'ordering': ['-created_at'],
            },
        ),
    ]
