# Generated by Django 5.2.10 on 2026-02-17 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
        ('worksession', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='target',
        ),
        migrations.AddField(
            model_name='compliance',
            name='category',
            field=models.CharField(choices=[('HELMET', 'Helmet'), ('VEST', 'Vest'), ('SHOES', 'Shoes')], default='HELMET', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliance',
            name='worksession',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='worksession.worksession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compliance',
            name='detected_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='is_complied',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='original_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=10)),
                ('image_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
                ('worksession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='worksession.worksession')),
            ],
            options={
                'db_table': 'photo',
                'ordering': ['-created_at'],
            },
        ),
    ]
