# Generated by Django 5.2.10 on 2026-02-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='category',
            field=models.CharField(choices=[('HELMET', 'Helmet'), ('VEST', 'Vest'), ('GLOVE', 'Glove')], max_length=10),
        ),
    ]
