# Generated by Django 5.2.10 on 2026-02-19 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'worksite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='READY', max_length=20)),
                ('fullcam_video', models.CharField(blank=True, max_length=255, null=True)),
                ('bodycam_video', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='worksession.worksite')),
            ],
            options={
                'db_table': 'worksession',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HEAD', 'Head Manager'), ('RELATED', 'Related Person'), ('WORKER', 'Worker')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
                ('worksession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='worksession.worksession')),
            ],
            options={
                'db_table': 'worksession_member',
                'unique_together': {('worksession', 'user')},
            },
        ),
    ]
