# Generated by Django 5.2.10 on 2026-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='name',
            field=models.CharField(default='d', max_length=200),
            preserve_default=False,
        ),
    ]
