name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - main  # Or 'dev', depending on when you want to trigger this
    paths:
      - 'backend/**' # Only run if backend code changes
      - 'deploy-azure.yaml'

env:
  ACR_LOGIN_SERVER: riskpulseacr.azurecr.io # Replace with your ACR name
  IMAGE_NAME: riskpulse-backend
  CONTAINER_APP_NAME: api-riskpulse
  RESOURCE_GROUP: rg-riskpulse

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code
      - name: Checkout GitHub Actions
        uses: actions/checkout@v3

      # 2. Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Log into your Azure Container Registry
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 4. Build and Push the Docker Image
      - name: Build and push container image to ACR
        run: |
          # Go to the backend directory where the Dockerfile is
          cd backend
          
          # Build the image and tag it with the Github SHA (unique ID)
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          
          # Push it to ACR
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # 5. Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --name ${{ env.CONTAINER_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
              --set-env-vars \
                "DB_NAME=riskpulse_db" \
                "DB_USER=${{ vars.DB_USER }}" \
                "DB_HOST=${{ secrets.MYSQL_HOST }}" \
                "DB_PORT=${{ vars.DB_PORT }}" \
                "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
                "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" \
                "MYSQL_PORT=3306" \
                "MYSQL_DATABASE=${{ vars.DB_NAME }}" \
                "MYSQL_USER=${{ vars.DB_USER }}" \
                "MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }}" \
                "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" \
                "REDIS_HOST=${{ secrets.REDIS_HOST }}" \
                "REDIS_PORT=6380" \
                "AZURE_STORAGE_ACCOUNT_NAME=striskpulse" \
                "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
                "AZURE_BLOB_CONTAINER=images" \
                "AZURE_SAS_TTL_MINUTES=10" \
                "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
                "OPENAI_MODEL=gpt-4o-mini"